# Generated by Django 4.1.5 on 2023-03-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_owletbalance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OwletBalance",
            new_name="OwletAccount",
        ),
    ]
