# Generated by Django 4.1.5 on 2023-03-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_owletbalance_owletaccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OwletAccount",
        ),
    ]
