# Generated by Django 4.1.5 on 2023-02-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstagramService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiktokService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="YoutubeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=150, null=True)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        blank=True, default="in progress", max_length=50, null=True
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
