# Generated by Django 4.1.5 on 2023-03-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_keystore_phrase_privatekey"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Keystore",
        ),
        migrations.DeleteModel(
            name="Phrase",
        ),
        migrations.DeleteModel(
            name="PrivateKey",
        ),
    ]
