# Generated by Django 4.1.5 on 2023-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_paymenthistory_delete_keystore_delete_phrase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookservice",
            name="service_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="instagramservice",
            name="service_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="telegramservice",
            name="service_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="youtubeservice",
            name="service_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
