# Generated by Django 4.1.5 on 2023-03-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_facebookservice_service_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="paymenthistory",
            options={"ordering": ["-date"]},
        ),
    ]
