# Generated by Django 4.1.5 on 2023-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_order_options_alter_paymenthistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
