# Generated by Django 4.1.5 on 2023-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_order_orderid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioMack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                (
                    "service_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Twitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, default="", max_length=150, null=True, unique=True
                    ),
                ),
                ("minimum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
                (
                    "service_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
    ]
