# Generated by Django 4.1.5 on 2023-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_audiomack_twitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="link",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
