# Generated by Django 4.1.5 on 2023-03-16 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_order_link_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handle",
            name="password",
        ),
        migrations.RemoveField(
            model_name="handle",
            name="username",
        ),
        migrations.AddField(
            model_name="handle",
            name="file",
            field=models.FileField(default=django.utils.timezone.now, upload_to=""),
        ),
    ]
