# Generated by Django 4.1.5 on 2023-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_handle_password_remove_handle_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handle",
            name="file_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
