# Generated by Django 4.1.5 on 2023-03-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_handle_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refil_status",
            field=models.BooleanField(default=False),
        ),
    ]
