# Generated by Django 4.1.5 on 2023-03-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_order_refil_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="handle",
            old_name="file_name",
            new_name="years",
        ),
    ]
