# Generated by Django 4.1.5 on 2023-04-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_file_name_handle_years"),
    ]

    operations = [
        migrations.RenameField(
            model_name="handle",
            old_name="years",
            new_name="type_of",
        ),
    ]
