# Generated by Django 4.1.5 on 2023-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_years_handle_type_of"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.URLField()),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("Facebook", "Facebook"),
                            ("Google Voice", "Google Voice"),
                            ("Instagram", "Instagram"),
                            ("Twitter", "Twitter"),
                            ("Premium VPN", "Premium VPN"),
                            ("Facebook ADS", "Facebook ADS"),
                            ("Netflix", "Netflix"),
                            ("Tiktok", "Tiktok"),
                            ("Gmail", "Gmail"),
                            ("Snapchat", "Snapchat"),
                        ],
                        default=("Facebook", "Facebook"),
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("UK", "UK")],
                        default=("Facebook", "Facebook"),
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=150, null=True),
                ),
                ("price", models.FloatField()),
            ],
        ),
    ]
