# Generated by Django 4.1.5 on 2023-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
