# Generated by Django 4.1.5 on 2023-04-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_account_is_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="logo",
        ),
    ]
