# Generated by Django 4.1.5 on 2023-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_account_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[("USA", "USA")],
                default=("Facebook", "Facebook"),
                max_length=150,
            ),
        ),
    ]
