# Generated by Django 4.1.5 on 2023-04-07 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_account_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="file",
            field=models.FileField(default=django.utils.timezone.now, upload_to=""),
        ),
    ]
