# Generated by Django 4.1.5 on 2023-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_account_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[("Male Fb Dating", "Male Fb Dating")],
                default=("Facebook", "Facebook"),
                max_length=150,
            ),
        ),
    ]
