# Generated by Django 4.1.5 on 2023-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_account_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="category",
        ),
        migrations.AddField(
            model_name="account",
            name="category",
            field=models.ManyToManyField(to="core.category"),
        ),
    ]
