# Generated by Django 4.1.5 on 2023-04-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_category_type_of"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="category",
        ),
        migrations.AddField(
            model_name="account",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
        ),
    ]
