# Generated by Django 4.1.5 on 2023-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_account_category_account_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
