# Generated by Django 4.1.5 on 2023-04-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_category_count_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="description",
        ),
        migrations.RemoveField(
            model_name="account",
            name="price",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
