# Generated by Django 4.1.5 on 2023-04-19 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0028_remove_account_description_remove_account_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type_of",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("Google Voice", "Google Voice"),
                    ("Instagram", "Instagram"),
                    ("Twitter", "Twitter"),
                    ("VPN", "VPN"),
                    ("Facebook ADS", "Facebook ADS"),
                    ("Netflix", "Netflix"),
                    ("Tiktok", "Tiktok"),
                    ("Gmail", "Gmail"),
                    ("Snapchat", "Snapchat"),
                    ("OLD FANPAGE", "OLD FANPAGE"),
                    ("Linkedin", "Linkedin"),
                ],
                default=("Facebook", "Facebook"),
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type_of",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("Google Voice", "Google Voice"),
                    ("Instagram", "Instagram"),
                    ("Twitter", "Twitter"),
                    ("VPN", "VPN"),
                    ("Facebook ADS", "Facebook ADS"),
                    ("Netflix", "Netflix"),
                    ("Tiktok", "Tiktok"),
                    ("Gmail", "Gmail"),
                    ("Snapchat", "Snapchat"),
                    ("OLD FANPAGE", "OLD FANPAGE"),
                    ("Linkedin", "Linkedin"),
                ],
                default=("Facebook", "Facebook"),
                max_length=150,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("account", models.CharField(blank=True, max_length=150, null=True)),
                ("file", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
