# Generated by Django 4.1.5 on 2023-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
