# Generated by Django 4.1.5 on 2023-04-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_purchasehistory_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenthistory",
            options={
                "ordering": ["-date"],
                "verbose_name": "Payment History",
                "verbose_name_plural": "Payment Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasehistory",
            options={
                "verbose_name": "Purchase History",
                "verbose_name_plural": "Purchase Histories",
            },
        ),
    ]
