# Generated by Django 4.1.5 on 2023-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_paymenthistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
