# Generated by Django 4.1.5 on 2023-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_account_file_alter_account_type_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_of',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Facebook Dating', 'Facebook Dating'), ('Google Voice', 'Google Voice'), ('New Instagram', ' New Instagram'), ('Old Instagram', ' Old Instagram'), ('Twitter', 'Twitter'), ('VPN', 'VPN'), ('Facebook ADS', 'Facebook ADS'), ('Netflix', 'Netflix'), ('Tiktok', 'Tiktok'), ('Gmail', 'Gmail'), ('Snapchat', 'Snapchat'), ('OLD FANPAGE', 'OLD FANPAGE'), ('Linkedin', 'Linkedin')], default=('Facebook', 'Facebook'), max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_of',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Facebook Dating', 'Facebook Dating'), ('Google Voice', 'Google Voice'), ('New Instagram', ' New Instagram'), ('Old Instagram', ' Old Instagram'), ('Twitter', 'Twitter'), ('VPN', 'VPN'), ('Facebook ADS', 'Facebook ADS'), ('Netflix', 'Netflix'), ('Tiktok', 'Tiktok'), ('Gmail', 'Gmail'), ('Snapchat', 'Snapchat'), ('OLD FANPAGE', 'OLD FANPAGE'), ('Linkedin', 'Linkedin')], default=('Facebook', 'Facebook'), max_length=150),
        ),
    ]
